services:
  - type: web
    name: youtubecreative1
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app.py
    envVars:
      - key: ALLOWED_ORIGIN
        value: '*'
